version: '3.8'

services:
  ytcapt:
    build: .
    container_name: ytcapt
    ports:
      - "8001:8000" # External:Internal port mapping
    environment:
      - PRODUCTION_MODE=true # Run in production mode (set to false for debugging)
    restart: unless-stopped
